package main

import (
	"log"
	"net"

	// to access the code that was generated by protoc
	pb "github.com/mayankav/grpc-go-demo/greet/proto"
	"google.golang.org/grpc"
)

var addr string = "localhost:5051"

type Server struct {
	// server generated by grpc plugin of protoc i.e. protoc-gen-go-grpc
	pb.GreetServiceServer
}

func main() {
	lis, err := net.Listen("tcp", addr)

	if err != nil {
		log.Fatalf("Failed to listen on: %v\n", err)
	}

	log.Printf("Listening on: %s\n", addr)

	s := grpc.NewServer()
	// register the GreetServiceServer - server generated by grpc plugin of protoc i.e. protoc-gen-go-grpc
	pb.RegisterGreetServiceServer(s, &Server{})
	if err = s.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v\n", err)
	}
}
