package main

import (
	"log"
	"net"

	"google.golang.org/grpc"

	pb "github.com/mayankav/grpc-go-demo/calculator/proto"
)

var addr string = "localhost:5052"

type Server struct {
	// server generated by grpc plugin of protoc i.e. protoc-gen-go-grpc
	pb.CalcServiceServer
}

func main() {
	lis, err := net.Listen("tcp", addr)

	if err != nil {
		log.Fatalf("Failed to listen on: %v\n", addr)
	}

	log.Printf("Listening on: %v\n", addr)

	s := grpc.NewServer()
	// register the CalcServiceServer - server generated by grpc plugin of protoc i.e. protoc-gen-go-grpc
	pb.RegisterCalcServiceServer(s, &Server{})
	if err = s.Serve(lis); err != nil {
		log.Fatalf("Failed to serve: %v\n", err)
	}
}
